---

- name: install latest device-mapper-libs, lvm2 & xfsprogs
  package:
    name: ["device-mapper-libs", "xfsprogs", "lvm2"]
    state: latest

- name: install python3
  package:
    name: python3
    state: present

- name: create directory for volume configs
  file:
    state: directory
    path: /etc/filesystems.d
    mode: 0755

- name: copy volume configuration file
  template:
    src: templates/volume-group.conf.j2
    dest: /etc/filesystems.d/10-volume-group.conf

- name: install storage-setup
  include_tasks: install.yml
